### ISSUE TITLE
use

### ISSUE THREAD

**Issue by GNUXDAR** [renatoliveira/Python-RSA-cryptography-example#1]
Hello friend, how do I use the script to encrypt a file?

**Comment by renatoliveira** [comment]
You can use the script to encrypt a file by following the steps in the README. Specifically after creating the key files, you will see the example command in the "Encrypting a file" section. This script runs from the command line only, but you should be able to check the source and write a version of it that runs in a different way if you need.

**Comment by GNUXDAR** [comment]
It's not working for me. I was able to generate the key pair, but when I try to encrypt the file, it gives me an error "No such file or directory: 'file'."

**Comment by renatoliveira** [comment]
> It's not working for me. I was able to generate the key pair, but when I try to encrypt the file, it gives me an error "No such file or directory: 'file'."
> 
> 

Are you sure your file (that you want to encrypt) is named just "file" and that you are referencing it from the correct directory?

**Comment by GNUXDAR** [comment]
"I renamed the file to 'my file name'. it's correct?

**Comment by GNUXDAR** [comment]
What should I do to make the file work correctly?

**Comment by renatoliveira** [comment]
> "I renamed the file to 'my file name'. it's correct?
> 
> 

The name of the file is not important. You should replace it where it says "file" in the sample command. 

Depending on your operating system the syntax in the command line might be a little different. I recommend not to use spaces in the file name. Look up online how to use your OS's command line for more info.

**Comment by GNUXDAR** [comment]
Thanks, I only encrypt .txt files. I was trying something else. Thank you very much for responding, great.
